apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.domain }}-wilduck-certificate
  labels:
    {{- include "wildduck.wildduck.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ .Values.tls.domain }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
  secretName: {{.Values.tls.domain }}-wildduck

