apiVersion: v1
kind: Service
metadata:
  name: {{include "wildduck.wildduck.fullname" .}}-imap-service
  labels: {{- include "wildduck.wildduck.labels" . | nindent 4}}
spec:
  type: {{.Values.wildduck.service.imapType}}
  ports:
    - port: {{.Values.wildduck.service.imapPort}}
      targetPort: imap
      protocol: TCP
      name: imap
  selector: {{- include "wildduck.wildduck.selectorLabels" . | nindent 4}}
