apiVersion: v1
kind: Service
metadata:
  name: {{include "wildduck.wildduck.fullname" .}}-http-service
  labels: {{- include "wildduck.wildduck.labels" . | nindent 4}}
spec:
  type: {{.Values.wildduck.service.httpType}}
  ports:
    - port: {{.Values.wildduck.service.httpPort}}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "wildduck.wildduck.selectorLabels" . | nindent 4}}
