apiVersion: v1
kind: Service
metadata:
  name: {{include "wildduck.wildduck.fullname" .}}-pop3-service
  labels: {{- include "wildduck.wildduck.labels" . | nindent 4}}
spec:
  type: {{.Values.wildduck.service.pop3Type}}
  ports:
    - port: {{.Values.wildduck.service.pop3Port}}
      targetPort: pop3 
      protocol: TCP
      name: pop3
  selector: {{- include "wildduck.wildduck.selectorLabels" . | nindent 4}}
