apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "wildduck.rspamd.fullname" . }}-override-configmap"
data:
  dmarc.conf: |-
    actions = {
        quarantine = "add_header";
        reject = "reject";
    }
  redis.conf: |-
    servers = "{{ .Values.redis.host }}:{{ .Values.redis.port }}";
    password = "{{ .Values.redis.password }}"
    db = "4";