apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "wildduck.haproxy.fullname" . }}-configmap"
data:
  haproxy.cfg: |-
    frontend bramdev.nl.smtp.frontend
      bind :587 ssl crt /etc/ssl/certs/tls.crt
      default_backend bramdev.nl.smtp.backend

    frontend bramdev.nl.smtp.frontend
      bind :995 ssl crt /etc/ssl/certs/tls.crt
      default_backend bramdev.nl.pop3.backend

    frontend bramdev.nl.imap.frontend
      bind :993 ssl crt /etc/ssl/certs/tls.crt
      default_backend bramdev.nl.imap.backend

    backend bramdev.nl.smtp
      server haraka wildduck-haraka-service:25

    backend bramdev.nl.pop3
      server imap wildduck-pop3-service:110

    backend bramdev.nl.imap
      server imap wildduck-imap-service:143
