apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "wildduck.haproxy.fullname" . }}-configmap"
data:
  haproxy.cfg: |-
    frontend smtp.frontend
      bind :587 ssl crt /etc/ssl/certs/tls.crt
      default_backend smtp.backend

    frontend pop3.frontend
      bind :995 ssl crt /etc/ssl/certs/tls.crt
      default_backend pop3.backend

    frontend imap.frontend
      bind :993 ssl crt /etc/ssl/certs/tls.crt
      default_backend imap.backend

    backend smtp.backend
      server haraka wildduck-haraka-service:25

    backend pop3.backend
      server imap wildduck-pop3-service:110

    backend imap.backend
      server imap wildduck-imap-service:143

