apiVersion: v1
kind: Service
metadata:
  name: {{include "wildduck.haproxy.fullname" .}}
  labels: {{- include "wildduck.haproxy.labels" . | nindent 4}}
spec:
  type: {{.Values.haproxy.service.smtpsType }}
  ports:
    - port: {{.Values.haproxy.service.smtpsPort }}
      targetPort: smtps
      protocol: TCP
      name: smtps
  selector: {{- include "wildduck.haproxy.selectorLabels" . | nindent 4}}
