apiVersion: v1
kind: Service
metadata:
  name: {{include "wildduck.duckyapi.fullname" .}}
  labels: {{- include "wildduck.duckyapi.labels" . | nindent 4}}
spec:
  type: {{.Values.duckyapi.service.type}}
  ports:
    - port: {{.Values.duckyapi.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "wildduck.duckyapi.selectorLabels" . | nindent 4}}
